WITH TRIPS AS(

select 
RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) TRIP_DATE,
START_STATIO_ID AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL
from {{ source('demo', 'bike') }}
where RIDE_ID != 'RIDE_ID' AND ENDED_AT !='ENDED_AT' AND
STARTED_AT != 'started_at' AND STARTED_AT != '"started_at"'
) select * from TRIPS