WITH TRIPS AS(

select 
RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) TRIP_DATE,
START_STATIO_ID AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECONDS,TO_TIMESTAMP(ENDED_AT) , TO_TIMESTAMP(STARTED_AT)) AS TRIP_DURATION_SECONDS,

from {{ source('demo', 'bike') }}
where RIDE_ID != 'RIDE_ID'
limit 10
) select * from TRIPS